dist: trusty
sudo: false

language: go

install:
  # dep is used to manage dependencies
  - go get -u github.com/golang/dep/cmd/dep

go:
  - "1.8.x"
  - "1.9.x"
  - "1.10.x"
  - tip

go_import_path: github.com/Unleash/unleash-client-go

matrix:
  fast_finish: true
  allow_failures:
  - go: tip
script: 
  - make test
